export const persona = {
  nombre: 'Juan Manuel',
  apellido: 'Bigioni',
  edad: 30,
  sexo: 'masculino',
  email: 'john@doe.com',
  consistencia: 60,
  compatibilidad: 72,
  competencias: [
		{'Comunicación': Math.floor(Math.random() * 101)},
		{'Resolución de problemas': Math.floor(Math.random() * 101)},
		{'Liderazgo': Math.floor(Math.random() * 101)},
		{'Trabajo en equipo': Math.floor(Math.random() * 101)},
		{'Adaptabilidad': Math.floor(Math.random() * 101)},
		{'Creatividad': Math.floor(Math.random() * 101)},
		{'Pensamiento crítico': Math.floor(Math.random() * 101)},
		{'Organización': Math.floor(Math.random() * 101)},
		{'Innovación': Math.floor(Math.random() * 101)},
		{'Empatía': Math.floor(Math.random() * 101)},
		{'Negociación': Math.floor(Math.random() * 101)},
		{'Toma de decisiones': Math.floor(Math.random() * 101)},
		{'Gestión del tiempo': Math.floor(Math.random() * 101)},
		{'Comportamiento ético': Math.floor(Math.random() * 101)},
		{'Trabajo bajo presión': Math.floor(Math.random() * 101)},
		{'Inteligencia emocional': Math.floor(Math.random() * 101)},
		{'Gestión de conflictos': Math.floor(Math.random() * 101)},
		{'Atención al detalle': Math.floor(Math.random() * 101)},
		{'Creatividad digital': Math.floor(Math.random() * 101)},
		{'Pensamiento analítico': Math.floor(Math.random() * 101)},
		{'Comunicación digital': Math.floor(Math.random() * 101)},
		{'Capacidad de aprendizaje': Math.floor(Math.random() * 101)},
		{'Pensamiento estratégico': Math.floor(Math.random() * 101)},
		{'Visión de negocio': Math.floor(Math.random() * 101)},
		{'Gestión de proyectos': Math.floor(Math.random() * 101)}
	]
};